apiVersion: v1
kind: Binding
metadata:
  name: nginx
target:
  apiVersion: v1
  kind: Node
  name: node01

# assing a node to existing pod
# sends post request to a pods binding api
# kubectl get pods --namespace kube-system 
# to check the status of different k8s components
## whn bindng existing pod to a node 
# pod  is already in a running sttate and running pod can't move from one node to another so 
# we have to either delete pod or replace the pod
# pod definintion file



# Taint n Tolerations alias tnt
# tnt don't tell pod to go on which node
# it tells node to accept only those pods which have tolerations 
# to the taint on the node
# $ kubectl taint nodes node-name key=value:taint-effect
# taint-effect No schedule
# prefer no schedule
# No execute 
# if the taint is applied after the pod create then those pods 
# keeps on running even 
# if we wish to filter those pods also 
# taint effect has to be set to NoExecute
# whn master nodes are setup they are already tainted
 