apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
    tier: front-end
spec:
  containers:
    - name: nginx-container
      image: nginx
      command:
        - "sleep"
        - "5000"
      ports:
        - containerPort: 8080
      envFrom: #ENV 
        - secretRef:
            name: app-secret
      env: #single ENV
        - name: App_color
          valueFrom:
            configMapKeyRef:
              key: App_color
              name: app_config
  volumes:
    - name: app-secret-volume
      secret:
        secretName: app-secret
      


# Entrypoint corresponds to command field
# CMD corresponds to args 
# both are provided as arrays 
# there are 3 ways to inject fromconfig maps 
# env inject specified key value from config map
# envFrom inject whole config map
# volumes 
