apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
    tier: front-end
spec:
  securityContext:
    runAsUser: 1000
  containers:
    - name: nginx-container
      image: nginx
      command:
        - "sleep"
        - "5000"
      ports:
        - containerPort: 8080
      envFrom: #ENV 
        - secretRef:
            name: app-secret
      env: #single ENV
        - name: App_color
          valueFrom:
            configMapKeyRef:
              key: App_color
              name: app_config
      securityContext:
        runAsUser: 1000
        capabilities:
          add: ["MAC_ADMIN"]
  tolerations:
    - key: "app"
      operator: "Equal"
      value: "blue"
      effect: "NoSchedule"
           
  serviceAccountName: dashboard-sa
  volumes:
    - name: app-secret-volume
      secret:
        secretName: app-secret
      persistentVolumeClaim:
        claimName: myclaim
  nodeSelector:
    size: Large


# Entrypoint corresponds to command field
# CMD corresponds to args 
# both are provided as arrays 
# there are 3 ways to inject fromconfig maps 
# env inject specified key value from config map
# envFrom inject whole config map
# volumes 
# Nodeselectors are used to place pods on a particular node
# scheduler match key value pais in nodeSelector property in pod definition file 
# with the labels defined in the node 
