apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol1
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath: # Not for production environment
    path: /data
  awsElasticBlockStore:
    volumeID: <volume_id>
    fsType: ext4
  persistentVolumeReclaimPolicy: Delete

# $ kubectl create -f pv-definition.yml
# Acts as another k8s object in namespace
# Persistent Vol and Persistent Vol Claims are two separate objects in k8s namespace

# PV is created by Admin and PVC are created by User
