apiVersion: v1
kind: ReplicationController
metadata: # metadata for replication controller
  name: my-app-rc 
  labels:
    app: my-app
    type: fornt-end
spec:
  template:
      metadata: # metadata for a pod
        name: my-app-pod
        labels:
          app: my-app
          type: fornt-end
      spec:
        containers:
          - name: nginx-contaienr
            image: nginx

  replicas: 3 # specifying number of pods running at all times 

# kubectl create -f replication-controller.yml
# kubectl get replicationcontroller
# kubectl get pods
