apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  db_host: sql
  db_user: admin
  db_password: olaola


# creation iss similarl to conig maps
# injection of secret also work the same way as config map
# if secret has to be injected as volumes
# each attribute of secret ic created as a file with value inside it
# secrest are encoded not encrypted so dnt push it on github
# secrets are not encrypted in etcd
# seecrets and configmaps aare not visible by get all command 
# secrets are namespaced resource 