

apiVersion: v1
kind: ServiceAccount
metadata:
  name: dashboard-sa


# Two types of account in k8s 
# user and service 
# service account used by applications such as prometheus and grafana 


# $ kubectl create serviceaccount <name>
# service account token is must be used by external app while 
# authenticating with k8s API
# token of the service account is stored as secret 
# service token can be mounted to the app if deployed on k8s
# service accoutnt of a pod can't be changed 
# When a pod is created default service account is automatically
# mounted to that pod with its token
# In case of deploywmnt serviceAccount of pod can be changed

# Before v 1.22 serviceAccount are created with non-expiry Token
# after v 1.24 serviceAcount are now created and to create a token anothewr 
# command has to be run 