apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql-h
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
  replicas: 5
  podManagementPolicy: Parallel

  volumeClaimTemplates:
  - metadata: 
      name: data-volume
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: google-storage
      resources:
        requests:
          storageClassName: 500Mi


# Statefulset doesn't delete PVC 
# it ensures the pod is attached to the same pvc as before
